/**
 * DEMO DATA FIXTURES ADAPTER
 * 
 * CRITICAL REQUIREMENT:
 * These static fixtures are imported directly from real outputs generated by the Python PCAP analyzer.
 * All fixture records here are explicitly flagged with `isDemo: true` and will be labeled "DEMO DATA"
 * in the user interface to ensure they are strictly separated from live production analysis results.
 */

import { AnalysisResult, SamplePcapInfo } from "../types/analyzer";

// Import authentic static fixtures from sample_reports/
import synScanJson from "../../sample_reports/syn_port_scan.json";
import dnsTunnelJson from "../../sample_reports/dns_tunneling.json";
import cleartextJson from "../../sample_reports/cleartext.json";
import baselineJson from "../../sample_reports/corporate_baseline.json";

export const SAMPLE_PCAP_LIST: SamplePcapInfo[] = [
  {
    id: "syn_port_scan",
    fileName: "syn_port_scan.pcap",
    title: "Vertical TCP SYN Port Reconnaissance Scan",
    description: "45 unacknowledged SYN connection attempts targeting diverse ports on 10.10.20.5.",
    threatCategory: "Reconnaissance",
    expectedFindings: 4,
    severityLevel: "HIGH",
  },
  {
    id: "dns_tunnel",
    fileName: "dns_tunneling_c2.pcap",
    title: "Covert DNS Tunneling & C2 Exfiltration",
    description: "110 high-entropy DNS queries transmitting encoded data chunks over UDP port 53.",
    threatCategory: "DNS Anomaly",
    expectedFindings: 3,
    severityLevel: "HIGH",
  },
  {
    id: "cleartext",
    fileName: "cleartext_credentials.pcap",
    title: "Unencrypted HTTP & Metasploit Port 4444",
    description: "Cleartext HTTP authentication request to /login.php and non-standard listener activity.",
    threatCategory: "Cleartext Communication",
    expectedFindings: 2,
    severityLevel: "LOW",
  },
  {
    id: "baseline",
    fileName: "corporate_baseline.pcap",
    title: "Benign Corporate Web & DNS Baseline",
    description: "Normal corporate browsing to Slack, GitHub, and Google with established TLS handshakes.",
    threatCategory: "Benign Baseline",
    expectedFindings: 0,
    severityLevel: "INFO",
  },
];

// Helper to normalize and attach isDemo flag
function normalizeResult(raw: any, reportName: string): AnalysisResult {
  const result: AnalysisResult = {
    ...raw,
    isDemo: true, // EXPLICITLY MARKED AS DEMO DATA
  };

  // Ensure metadata has profile information
  if (result.metadata) {
    if (!result.metadata.profile_name) result.metadata.profile_name = "default";
    if (!result.metadata.profile_source) result.metadata.profile_source = "built-in (default)";
    if (!result.metadata.sha256_hash && raw.integrity?.sha256) {
      result.metadata.sha256_hash = raw.integrity.sha256;
    }
  }

  // Ensure findings have both id and rule_id normalized
  if (Array.isArray(result.findings)) {
    result.findings = result.findings.map((f: any) => ({
      ...f,
      finding_id: f.finding_id || f.id || "F-000",
      rule_id: f.rule_id || f.detection_rule || "RULE-000",
    }));
  }

  return result;
}

export const DEMO_FIXTURES: Record<string, AnalysisResult> = {
  syn_port_scan: normalizeResult(synScanJson, "syn_port_scan_report.txt"),
  dns_tunnel: normalizeResult(dnsTunnelJson, "dns_tunneling_report.txt"),
  cleartext: normalizeResult(cleartextJson, "cleartext_report.txt"),
  baseline: normalizeResult(baselineJson, "corporate_baseline_report.txt"),
};
